insert into COURSE (ID, AUTHOR,NAME)
values (10001,'SANTHOSH','LEARN SPRING BOOT');
insert into COURSE (ID, AUTHOR,NAME)
values (10002,'SANTHOSH','LEARN FULLSTACK WITH REACT AND ANGULAR');
insert into COURSE (ID, AUTHOR,NAME)
values (10003,'SANTHOSH','LEARN AWS, GCP AND MS AZURE');
insert into MOVIE_REVIEWS(REVIEW_NUMBER,MOVIE_RATING,REVIEW)
values(1,5,'Awesome Movie');
insert into MOVIE_REVIEWS(REVIEW_NUMBER,MOVIE_RATING,REVIEW)
values(2,3,'Awesome Movie22');
insert into MOVIE_REVIEWS(REVIEW_NUMBER,MOVIE_RATING,REVIEW)
values(71,4,'Awesome Moviehgdfd');